/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMaterialSymbolsBook4Spark: typeof import('~icons/material-symbols/book4-spark.jsx')['default']
  const IconMaterialSymbolsChecklist: typeof import('~icons/material-symbols/checklist.jsx')['default']
  const IconMdiBookCheck: typeof import('~icons/mdi/book-check.jsx')['default']
  const IconMdiBookCheckBookCheck: typeof import('~icons/mdi/book-check-book-check.jsx')['default']
}
